In [2]:
import torch

In [3]:
# Scalars
scalar = torch.tensor(7)
print(scalar.item())

7


In [4]:
# Vectors
vector = torch.tensor([7,9])

print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 9])
1
torch.Size([2])


In [5]:
# Matrices
matrix = torch.tensor([[1,2], [3,4]])

print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [6]:
# Tensor
tensor = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
3
torch.Size([2, 3, 3])


In [7]:
# Tensors with random numbers

randomTensor = torch.rand(size=(224,224,3))
print(randomTensor.ndim, randomTensor.shape)

3 torch.Size([224, 224, 3])


In [8]:
# Range tensors

zero_to_ten = torch.arange(start=0, end=10, step=1)

print(zero_to_ten)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
# Copy shape of tensor
sameShapeTensor = torch.ones_like((zero_to_ten))

print(sameShapeTensor)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [10]:
# Tensors with specific datatypes

float32Tensor = torch.tensor([3, 9.2, 6.7], dtype=torch.float64, device=None, requires_grad=False)

print(float32Tensor)
float32Tensor.dtype

tensor([3.0000, 9.2000, 6.7000], dtype=torch.float64)


torch.float64

In [11]:
# info from tensors

print(float32Tensor.shape)
print(float32Tensor.dtype)
print(float32Tensor.device)


torch.Size([3])
torch.float64
cpu


In [12]:
%%time
# Matrix multiplication
tensor = torch.tensor([1,2,3,4,5])

product = tensor @ tensor

print(product)

tensor(55)
CPU times: total: 0 ns
Wall time: 999 μs


In [13]:
# Transposing

tensor1 = torch.tensor([[1,2,3], [4,5,6]])

tensor1.T



tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [14]:
#
torch.manual_seed(42)
tensor1 = torch.tensor([1,2,3], dtype=torch.float32)
# weights = torch.tensor([])


fflayer = torch.nn.Linear(in_features=3, out_features=5, bias=True)

x = tensor1

output = fflayer(x)

output

tensor([0.9125, 1.0719, 2.0093, 0.6347, 1.5653], grad_fn=<ViewBackward0>)

In [20]:
# Change dtype of data in tensor with changing tensor
tensor = torch.tensor([1,2,3,4,5])

print(tensor.type(torch.float32))

print(tensor)

# create identical tensor but with new dtype
tensorNewDtype = tensor.type(torch.float64)
print(tensorNewDtype.dtype)

tensor([1., 2., 3., 4., 5.])
tensor([1, 2, 3, 4, 5])
torch.float64


In [16]:
# positional max/min

tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [59]:
# Reshaping, stacking, squeezing and unsqueezing

tensor = torch.ones((3,2))
print(tensor.shape)

reshapedTensor = torch.reshape(tensor, (2,3))

print(tensor, '\n''\n', reshapedTensor)
print()
# Views are a computationally inexpensive way to slice tensors without changing the original tensor
view = tensor.view((1, 6))
print(view, '\n''\n', tensor)


print()
# stackedTensor = torch.stack([tensor, tensor], dim=0)
stackedTensor = torch.cat([tensor, tensor], dim=1)
print("Stacked tensor: ", stackedTensor)
print(stackedTensor.ndim, stackedTensor.shape)

torch.Size([3, 2])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) 

 tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 1., 1., 1., 1., 1.]]) 

 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

Stacked tensor:  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
2 torch.Size([3, 4])
