In [1]:
import torch

In [16]:
# Scalars
scalar = torch.tensor(7)
print(scalar.item())

7


In [43]:
# Vectors
vector = torch.tensor([7,9])

print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 9])
1
torch.Size([2])


In [42]:
# Matrices
matrix = torch.tensor([[1,2], [3,4]])

print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [51]:
# Tensor
tensor = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
3
torch.Size([2, 3, 3])


In [83]:
# Tensors with random numbers

randomTensor = torch.rand(size=(224,224,3))
print(randomTensor.ndim, randomTensor.shape)

3 torch.Size([224, 224, 3])
